### ISSUE TITLE
Any chance you'd consider an alternate license?

### ISSUE THREAD

**Issue by greglandrum** [mittinatten/freesasa#11]
Hi Simon,

I found out about freesasa because of the F1000Research paper and think it looks great. Thanks for making it available!

I would like to do an integration with the RDKit, which could certainly use this kind of functionality, but the fact that freesasa is covered by the GPL makes that impossible. Would you consider choosing another, more collaboration friendly, license for the project?

Thanks,
-greg

**Comment by mittinatten** [comment]
Hi Greg,
Glad to hear you like it, and great if it can be useful!

I agree that it might make sense to loosen the license somewhat. Will get back to you soon.

Simon

**Comment by greglandrum** [comment]
Thanks Simon.

**Comment by mittinatten** [comment]
Ok, MIT-licensed in the dev branch (6cf5826cc9a464277a), will propagate to master shortly.

**Comment by mittinatten** [comment]
Released: https://github.com/mittinatten/freesasa/releases/tag/1.0.3

**Comment by greglandrum** [comment]
Thanks Simon!
I'll let you know when I get the RDKit connector done.
This won't be in the next few weeks, but I'll certainly do something.
