### ISSUE TITLE
Cython not found with --enable-python-bindings

### ISSUE THREAD

**Issue by jaredsagendorf** [mittinatten/freesasa#15]
Hello, I'm trying to upgrade to version 2.0 (I had the previous version installed and working fine), with python-binding enabled (I am using freesasa as a python library).

I am running the configure script like so:
```
./configure --prefix="~/anaconda2/pkgs/freesasa-py27_0" --exec-prefix="~/anaconda2/pkgs/freesasa-py27_0" --enable-python-bindings  --with-python="~/anaconda2/bin/python2.7" --disable-json CFLAGS=-fPICgrep
```
This is identical to how I would run it before (except for the --disable-json flag), and everything was fine. Now, I get the error:

```
checking for cython... cython
configure: error: Cython not available, can not build Python bindings
```
However, Cython is definitely available, and is located in the system path, and the previous version of freesasa did not have any trouble finding it. 

What has changed that could be causing this, and how can I fix it? Thank you, and this is a great tool.

**Comment by jaredsagendorf** [comment]
So I found a fix. I replace the following lines in configure.ac

```
if test "x$enable_python_bindings" = "xyes" ; then
  AC_CHECK_PROG([PYTHON], [$python_bin], [$python_bin])
  AC_CHECK_PROG([CYTHON], [cython], [cython])
  if test $CYTHON && test $PYTHON ; then
    AM_CONDITIONAL([HAVE_CYTHON], true)
  fi
  AM_COND_IF([HAVE_CYTHON],[],[AC_MSG_ERROR([Cython not available, can not build Python bindings])])
fi
```
with

```
if test "x$enable_python_bindings" = "xyes" ; then
  AC_CHECK_PROG(PYTHON, python, $python_bin)
  AC_CHECK_PROG(CYTHON, cython, cython)
  AM_CONDITIONAL([HAVE_CYTHON], [test -n "$CYTHON" && test -n "$PYTHON"])
  AM_COND_IF([HAVE_CYTHON],[],[echo "Cython not available, will not build Python bindings"])
else
  AM_CONDITIONAL([HAVE_CYTHON],false)
fi
```

I don't have any insight into why one works and one doesn't, but maybe someone can look into it.

**Comment by mittinatten** [comment]
Hi, thanks for the heads-up! Didn't get this error myself (assume this is sensitive to version of autoconf or some other detail of the system used). Your solution makes sense to me, will do some checks to make sure it doesn't break anything else.

**Comment by mittinatten** [comment]
Could you give me the details of your system so I can try to reproduce the error? Version of autoconf, operating system, perl, m4, cython and python.

**Comment by mittinatten** [comment]
Also, does it still work if you keep the square brackets around the arguments in `AC_CHECK_PROG(...)`?

**Comment by mittinatten** [comment]
I committed something similar to your change to the dev branch (3cdcebd). Can you check if that works for you?

**Comment by mittinatten** [comment]
Closing this, let me know if you have further problems!
