### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by molsim** [mittinatten/freesasa#19]
Hi Simon,
I wonder if you are considering to make a minor release of the current FreeSASA version that would include a tar file with autoconf generated files.

My project currently depends on the latest version of FreeSASA and it would be easier to direct the users to download a FreeSASA release and compile it, that to ask them to clone the repo and then use autoconf, which is not easy to install on all platforms.

Thanks,
Alex

**Comment by mittinatten** [comment]
Yes, that was in the pipeline actually, and I think everything is ready, including updated documentation, just haven't gotten around to it. I can try to get it out during the weekend. If you need something straight away, the command `make dist` creates an archive with all the necessary files.

**Comment by molsim** [comment]
Thanks, that would be great!
We are contemplating to putting our project to the NCBI GitHub page, so from the licensing perspective it would be cleaner to direct the users to the FreeSASA release, than to provide adhoc archive with the latest version of FreeSASA inside the repo.

**Comment by mittinatten** [comment]
Ok, 2.0.1 is available here: https://github.com/mittinatten/freesasa/releases/tag/2.0.1 and the documentation and tarball at http://freesasa.github.io are also up to date with the changes.
