### ISSUE TITLE
python bindings under windows

### ISSUE THREAD

**Issue by vlado-s** [mittinatten/freesasa#21]
Hi,
I develop my python3 code and would like to interface it with your freeSASA code. Dominantly I work under windows (7 & 8) with the Anaconda/spyder editor. I did not find any comment on how to compile & build your code under the Windows environment. Another option is my Ubuntu 14.x cluster where I can compile & build and also run it (so far without python bindings). I want my code to be platform independent and would be nice if it cold be interfaced with your code also on as many platforms as possible (at least the most frequent in science community - linux, win & mac)). Any hint? Thanks'.
Cheers,
Vlado

---
P.S.: I'm not doing any rip-off of your code :) I just would like to include it as one option in the work-flow of my PDB analysis to run your code. So I would recommend the user to install freeSASA to be able to use that option.

**Comment by mittinatten** [comment]
I have no experience doing development in Windows. The library is C99, but uses some GNU extensions (which might be available in Windows). I would expect the library to be compilable with the Microsoft C compiler/Visual Studio with no or minor adjustments. Unfortunately I don't have access to any Windows machines to do any testing.

I noticed that this fork https://github.com/bp-kelley/freesasa was adjusted for Windows (although it's a bit outdated now), maybe some lessons can be learned from there (or the author can be contacted).

**Comment by mittinatten** [comment]
This is the branch https://github.com/bp-kelley/freesasa/commits/msvc-fixes

**Comment by vlado-s** [comment]
Thank you for the reply. The author of the forked version wrote this:

 

I have a windows compilable version of free dads here:
https://github.com/bp-kelley/freesasa/archive/msvc-fixes.tar.gz
It's sub optimal, but it seems to work.
It has not had updates for a year and is really not maintained, I haven't tried to push the updates upstream yet, so this is a good reminder.



So maybe he will modify also your later version…

**Comment by mittinatten** [comment]
It seems you should be able to use Cython in Windows with Visual Studio https://github.com/cython/cython/wiki/InstallingOnWindows
https://github.com/cython/cython/wiki/CythonExtensionsOnWindows

As I wrote at 126df0aaa making it MS compatible shouldn't be too hard. Another option is of course to use Cygwin or MinGW.

**Comment by mittinatten** [comment]
Closing this issue, since Python 3-compatibility has been fixed and Windows compatibility belongs under #22.

**Comment by mittinatten** [comment]
Don't know if it's still relevant for you, but I have made a test PyPi package that should be windows compatible (although I don't have the tools to actually test): https://test.pypi.org/project/freesasa/

**Comment by vlado-s** [comment]
Hi,

Thank you for the devotion. My current code utilizes SASA data by your freeSASA package generated before the execution of my code. So far I did not implement it in my code as a command. Maybe I will do so in the next release (if people show desire).
