### ISSUE TITLE
FreeSasa unable to analyze nmr structures of RNA

### ISSUE THREAD

**Issue by drjsoundsgood** [mittinatten/freesasa#24]
I am running the following command:

freesasa xxx.pdb --format=pdb --join-models > xxx.txt,
(where xxx = 1anr, 2fey, 2n6x, 2n6w, 2n6t, 2n6s, 2m21, 28sr, 1a51)
but the SASA value for nearly everything is 0.
Some exceptions are 1elh (I also get a 'nan' error for some) and 1a4d. Not all have SASA values, but a good majority of them do.

The thing that all of these have in common is that they are NMR derived structures.

When I use a pdb file such as 357d.pdb (364d, 354d,1c2x) there are SASA values for nearly every atom. 1c2x is a cryo electron microscopy structure, and the other three are X-ray diffraction derived structures.

Why is SASA unable to gather surface accessibility for NMR structures?

Attached are the outputs for three examples: 1a4d, 1anr, and 357d.

[1a4d.txt](https://github.com/mittinatten/freesasa/files/1099566/1a4d.txt)
[1anr.txt](https://github.com/mittinatten/freesasa/files/1099567/1anr.txt)
[357d.txt](https://github.com/mittinatten/freesasa/files/1099568/357d.txt)

**Comment by mittinatten** [comment]
Hi,
The problem is probably `--join-models`, if you join NMR models you get a
very high density of atoms, and no single atom is very exposed. The best
option is to either use one single model (default) or treat them separately
using `--separate-models`.

Simon

**Comment by drjsoundsgood** [comment]
Hi Simon,

Yes, this was the solution to the issue.

However, when I try something like:

freesasa --separate-models --format=pdb 1anr.pdb

Only the first model's SASA is calculated? Is it not possible to link these two options?

**Comment by mittinatten** [comment]
It is not possible at the moment, but it makes sense. I don't think it will be difficult to add, but I'm not sure if I'll have time to do it before august.

**Comment by mittinatten** [comment]
I created a specific issue for this feature (#25). Will close here. Reopen if anything else comes up.
