### ISSUE TITLE
Problems with PDB output using --separate-models

### ISSUE THREAD

**Issue by mittinatten** [mittinatten/freesasa#25]
Only the first model is included in the PDB output when using the CLI option `--separate-models` (see #24).

**Comment by drjsoundsgood** [comment]
Thanks for looking into this. In the meantime, I wrote a few scripts to get it done, so no rush/worries if you don't have time to look into it now.

**Comment by mittinatten** [comment]
Hi again,
Turns out the fix only involved a very minor change. 28d7e1d should fix this (in the dev-branch). I'll close the issue, feel free to reopen if the patch doesn't work as expected.

**Comment by mittinatten** [comment]
Merged the fix into the master branch too
