### ISSUE TITLE
Change README.md? Compiling 2.0.3 in Ubuntu 

### ISSUE THREAD

**Issue by pgbarletta** [mittinatten/freesasa#37]
Hi, I noticed the ```autoconf``` command did not show in the README. I actually had to do this to install in Ubuntu (since ```autoconf``` would complain about undefined macros):
``` 
autoreconf -i 
./configure
make
make install
```

**Comment by mittinatten** [comment]
It actually is, check line 47 in README. :)

**Comment by pgbarletta** [comment]
my bad! I'm used to run the commands that show up in the codeblock.
