### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sjkdenny** [mittinatten/freesasa#44]
Thanks for this great package. I'm having trouble installing. On a MacOS Mojave 10.14.3, the ./configure command gives the following error:

> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... ./install-sh -c -d
> checking for gawk... no
> checking for mawk... no
> checking for nawk... no
> checking for awk... awk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... configure: error: in `/Volumes/GoogleDrive/My Drive/software/freesasa-2.0.2':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details

I've attached my config.log file. Thanks for your help!
[config.log](https://github.com/mittinatten/freesasa/files/2968619/config.log)

**Comment by mittinatten** [comment]
Hi! Seems to be a problem with file permissions, you are not alllowed to
execute the test-file that configure produces. Do you have execution
permissions in the directory you are building in?

tors 14 mars 2019 kl. 22:56 skrev sjkdenny <notifications@github.com>:

**Comment by sjkdenny** [comment]
You are right, it works when I move the directory out of my google file stream. Thanks for your help!

**Comment by sjkdenny** [comment]
Again thanks for your quick reply earlier. Unfortunately, I'm still running into trouble. I now have the error "Library libxml2 not found:". I have tried installing the libxml2 library three different ways. 1) using conda (https://github.com/conda-forge/libxml2-feedstock), and while it shows up in my list of conda packages, the error continues to be thrown during the ./configure step, so perhaps this is an issue with conda? 2) Through http://xmlsoft.org/downloads.html. Their ftp server is broken and so I can't download, and downloading the MacOS binaries through one of their links only has the libxml, not the libxml2. 3) I downloaded from their git page, but they do not have a 'configure' file. The first step of their installation instructions was to run ./configure, so I'm scratching my head. Would your package still work without the libxml2 package? Do you ha
[config.log](https://github.com/mittinatten/freesasa/files/2973027/config.log)
ve any other advice? Thanks for your help. I attached my config.log just in case.

**Comment by mittinatten** [comment]
Glad to help!
You can build it without libxml using `./configure —disable-xml`. The same
for json (`—disable-json`).


fre 15 mars 2019 kl. 22:44 skrev sjkdenny <notifications@github.com>:

**Comment by sjkdenny** [comment]
success! thank you.

**Comment by mittinatten** [comment]
Good to hear!
