### ISSUE TITLE
How to prohibit FreeSASA warning

### ISSUE THREAD

**Issue by xiaolinpan** [mittinatten/freesasa#50]
Could you teach me to prohibit the waring message? thank you very much!
"""
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'TRP H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'TRP H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'TRP H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'TRP H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
FreeSASA: warning: atom 'TRP H' unknown, guessing element is ' H', and radius 1.100 A
FreeSASA: warning: guessing that atom 'N' is symbol ' N'
FreeSASA: warning: guessing that atom 'C' is symbol ' C'
FreeSASA: warning: guessing that atom 'C' is symbol ' C'
FreeSASA: warning: guessing that atom 'O' is symbol ' O'
FreeSASA: warning: guessing that atom 'C' is symbol ' C'
FreeSASA: warning: guessing that atom 'O' is symbol ' O'
FreeSASA: warning: guessing that atom 'H' is symbol ' H'
"""

**Comment by mittinatten** [comment]
How are you calling freesasa to get this?

**Comment by xiaolinpan** [comment]
I use `structure.addAtom()` to create a freesasa structure, and when i use atom symbol(C, H, O, N, etc) as atom name, it appeared, but the result calculated is right. I want to prohibit the message, could you help me? thank you very much!

**Comment by mittinatten** [comment]
The Python API does not support all options available yet, in the  C API you can suppress these specific warnings. I should probably expose that in Python as well.

You can override all warnings using:
```python
freesasa.setVerbosity(freesasa.nowarnings)
```

But, you should probably not include H atoms, the standard atomic radii are designed to work without hydrogens.

**Comment by xiaolinpan** [comment]
The hydrogen atom is added to match the atom index of other programs, thank you for your help!

**Comment by mittinatten** [comment]
Ok, I have created a task to add the mentioned functionality https://github.com/freesasa/freesasa-python/issues/15
