### ISSUE TITLE
Proper check for PDB format

### ISSUE THREAD

**Issue by JoaoRodrigues** [mittinatten/freesasa#6]
Another little issue: when reading a PDB file that has trimmed lines (shorter than 80 characters), which is actually quite common when dealing with processed PDBs from other programs, freesasa fails to read any atom info but attributes the class 'unknown' for the calculations. This makes things _extremely_ slow and isn't easy to figure out at first. I'd suggest you add a small check during the PDB reading routine to see not if any atoms were read (that is there) but if any were read properly. Otherwise, just set the line length to a minimum with occupancy as the last field.

**Comment by mittinatten** [comment]
I wasn't aware of this, ran a check of the PDB parsing functions against the entire PDB last year without any apparent errors. But perhaps these files are output from simulations etc? Anyway shouldn't be difficult to fix.

**Comment by mittinatten** [comment]
I think it is fixed now, committed a patch to the dev branch.

**Comment by JoaoRodrigues** [comment]
Thanks! I can give you a test file for unit testing if necessary.

**Comment by mittinatten** [comment]
Yes that would be good, thanks!

**Comment by JoaoRodrigues** [comment]
[Here](https://gist.github.com/JoaoRodrigues/56b33c0bc65261e134f0).

Running it gives this output:
```bash
## freesasa 0.1.1 ##
name: 3BZD.pdb
algorithm: Shrake & Rupley
probe-radius: 1.400000 A
n_thread: 1
n_testpoint: 100
time_elapsed: 41.485172 s
n_atoms: 2754

Total:   69762.71 A2
Polar:       0.00 A2
Apolar:  69762.71 A2
```

Fixing the lines and re-running:
```bash
## freesasa 0.1.1 ##
name: 3BZD_fixed.pdb
algorithm: Shrake & Rupley
probe-radius: 1.400000 A
n_thread: 1
n_testpoint: 100
time_elapsed: 0.090440 s
n_atoms: 2754

Total:   16064.83 A2
Polar:    8599.18 A2
Apolar:   7465.65 A2
```

**Comment by mittinatten** [comment]
With my patch the calculation runs normally and gives the same result for the trimmed file you provided, and one that I "fixed" by adding whitespace at the end of each line. But I my results are, in both cases,

    Total:   15955.55 A2
    Polar:    6543.36 A2
    Apolar:   9412.19 A2

Any chance a line was deleted or duplicated or something in your `3BZD_fixed.pdb`? Or have you been customizing atomic radii maybe?

**Comment by JoaoRodrigues** [comment]
The PDB file is just padded so that each line has 80 characters.




I did a fresh cloning of your master branch and ran it on the same 2 structures. I get different (although not 0) values for the classes:




```bash


joao@jr-mbp:src$ ./freesasa ~/Downloads/3BZD.pdb

## freesasa 0.1.1 ##

name: /Users/joao/Downloads/3BZD.pdb

algorithm: Shrake & Rupley

probe-radius: 1.400000 A

n_thread: 1

n_testpoint: 100

time_elapsed: 36.049243 s

n_atoms: 2754




Total:   74753.07 A2

Polar:     963.12 A2

Apolar:  73789.95 A2

joao@jr-mbp:src$ ./freesasa ~/Downloads/3BZD_fixed.pdb

## freesasa 0.1.1 ##

name: ...ao/Downloads/3BZD_fixed.pdb

algorithm: Shrake & Rupley

probe-radius: 1.400000 A

n_thread: 1

n_testpoint: 100

time_elapsed: 0.090429 s

n_atoms: 2754




Total:   15955.55 A2

Polar:    6543.36 A2

Apolar:   9412.19 A2

```

**Comment by JoaoRodrigues** [comment]
The PDB file is just padded so that each line has 80 characters.

I did a fresh cloning of your master branch and ran it on the same 2 structures. I get different (although not 0) values for the classes:

```bash
joao@jr-mbp:src$ ./freesasa ~/Downloads/3BZD.pdb
## freesasa 0.1.1 ##
name: /Users/joao/Downloads/3BZD.pdb
algorithm: Shrake & Rupley
probe-radius: 1.400000 A
n_thread: 1
n_testpoint: 100
time_elapsed: 36.049243 s
n_atoms: 2754

Total:   74753.07 A2
Polar:     963.12 A2
Apolar:  73789.95 A2
joao@jr-mbp:src$ ./freesasa ~/Downloads/3BZD_fixed.pdb
## freesasa 0.1.1 ##
name: …ao/Downloads/3BZD_fixed.pdb
algorithm: Shrake & Rupley
probe-radius: 1.400000 A
n_thread: 1
n_testpoint: 100
time_elapsed: 0.090429 s
n_atoms: 2754

Total:   15955.55 A2
Polar:    6543.36 A2
Apolar:   9412.19 A2
```

**Comment by mittinatten** [comment]
Ok, but then we get consistent results. I added your file to the unit tests. Thanks for pointing this out!

**Comment by mittinatten** [comment]
Will add it to the master branch within a few days. In the mean-time you can change the number 78 to 54 on line 66 in `pdb.c` if you don't want to use the dev branch.

**Comment by JoaoRodrigues** [comment]
Thanks!

**Comment by mittinatten** [comment]
Decided to add it as a minor release 0.1.2 in master.
