### ISSUE TITLE
Default classifier config-file missing MSE

### ISSUE THREAD

**Issue by swanss** [mittinatten/freesasa#66]
Hi, I believe MSE (selenomethionine), which occurs in the PDB with some frequency, is missing from `protor.config`. Would it be possible to add this, and perhaps some of the other not-so-uncommon non-canonical amino acids?

**Comment by swanss** [comment]
I read more of the documentation and realized that the radii defined in `protor.config` are from Tsai et. al, so it wouldn't make sense to just add new values.

How do you recommend I handle non-canonical amino acids? For context, I wrote a C++ wrapper class that calls functions from the freesasa library. I'm able to add atoms from non-canonical amino acids to the freesasa structure (using default options), and oftentimes even if the amino acid is unknown, the proper atom type is guessed. The issue is that, for some reason, when getting the total area from the freesasa residue node the program encounters a segmentation fault. My apologies is this is a simple mistake on my part.

**Comment by mittinatten** [comment]
Hi,
Regarding MSE, it should be possible to add to the standard config.
Selenocysteine (SEC) is already there, so this should be fairly
straightforward. I’ll look into it later this week.

I would probably need to see a code snippet to help you with the segfault,
but typically this should only happen if you access the node after it has
been freed, or possibly if you traverse the tree the wrong way. Does the
error only occur for unknown residues, or for all types?

ons 22 sep. 2021 kl. 06:10 skrev swanss ***@***.***>:

**Comment by mittinatten** [comment]
Hi,
I have added support for selenomethionine, thanks for your request!

Don't know about the segfault. If that problem persists, can you open it as a new issue, with some code that I can use to reproduce it?

Simon
