### ISSUE TITLE
Compilation Warning: check not found

### ISSUE THREAD

**Issue by JoaoRodrigues** [mittinatten/freesasa#7]
The test libraries are mandatory for compiling the program. It would be nicer if these were an optional dependency. I've been bypassing this by commenting the PKG_CHECK_MODULES line in configure.ac but it should be fixed properly.

**Comment by mittinatten** [comment]
That's strange, I thought the `if HAVE_CHECK` line in `tests/Makefile.am` would prevent that. I'm still pretty new to autotools, so I'll have to do some research here.

**Comment by mittinatten** [comment]
Patched this in dev (541dcba1ffa). It worked for me when I uninstalled check from my machine, could you try it too before I merge this into master?

**Comment by JoaoRodrigues** [comment]
Works!

**Comment by mittinatten** [comment]
Ok, thanks! Master is now up to date.
