### ISSUE TITLE
Getting same total SASA results with different given probes

### ISSUE THREAD

**Issue by ANUJGAHLAWAT** [mittinatten/freesasa#77]
CODE:

freesasa.Parameters({'probe-radius' : Probe})
freesasa.setVerbosity(freesasa.nowarnings)
structure = freesasa.Structure("G:/Anuj/delaulney trangulation/check different PDB/"+File+".pdb",{'hetatm' : True, 'hydrogen' : True})
result = freesasa.calc(structure)
print("pdb sasa :",result.totalArea())

PROBLEM:
I am getting the same results i.e.  17478.4794656937 for 3o7p.pdb using the result.totalArea() function even if I am giving different probes (1.4 A and 3.0 A) to the freesasa.Parameters function.
Generally, SASA for the PDB file should be lesser with a higher radius probe than that of a small probe.

Please provide your useful comments
Thank you

**Comment by mittinatten** [comment]
Hi, thanks for reaching out. That sounds like a bug. I'll have a look.

**Comment by mittinatten** [comment]
I checked this out and found the problem, you need to pass the parameters to the calc function. (in your code you create a parameters object and then discard it, so it won't be used by the calculation). Here's code that works for me:

```py
structure = freesasa.Structure("3o7p.pdb")
result = freesasa.calc(structure, freesasa.Parameters({'probe-radius': 3.0 }))
```

**Comment by ANUJGAHLAWAT** [comment]
Thank you for your response 😊
