### ISSUE TITLE
Problem with make

### ISSUE THREAD

**Issue by quocbao310** [mittinatten/freesasa#78]
Hi, 

I am trying to install freesasa program locally. I did it with the command:
./configure --prefix=/path/to/local --disable-json --disable-json --disable-xml

then I tried make command. I came up with an error.

cif.cc:11:10: fatal error: gemmi/cif.hpp: No such file or directory
   11 | #include <gemmi/cif.hpp>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [cif.o] Error 1
make[2]: Leaving directory `/scratch/panbazha/ngoquoc1/freesasa/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/scratch/panbazha/ngoquoc1/freesasa'
make: *** [all] Error 2

I am wondering what is the source of the problem. Thank you so much.

**Comment by mittinatten** [comment]
Hi,
You need to install the git submodules first (check the readme).

**Comment by quocbao310** [comment]
Hi,

My bad. I didnt read your instruction carefully. Thank you so much
