### ISSUE TITLE
Question: formula of alpha

### ISSUE THREAD

**Issue by cycle20** [mittinatten/freesasa#81]
Hi,
Can you explain how you get this formula?
![image](https://user-images.githubusercontent.com/46718432/172345705-f4884757-63ad-4021-87df-692ce85f6f53.png)
Could you provide the steps for this?
Thank you,
Csongor

_NOTE:_
On your documentation page there are misleading ```*``` in this formula: https://freesasa.github.io/doxygen/Geometry.html
![image](https://user-images.githubusercontent.com/46718432/172346926-c9f440d4-87ee-4145-8d11-cc1b641c9567.png)
It might be some kind of markup issue.
I hope my version reflects your intention.

**Comment by mittinatten** [comment]
Hi,
Thanks for reaching out! The error in the docs is regression: some editor plugin that doesn't understand LaTeX must have changed `_` to `*` (i.e. two ways to write *italic* in markdown). So this should not have passed through QA :). I have update the code and pushed the changes, the docs should be updated very soon.

The derivation is simply to apply the [law of cosines](https://en.wikipedia.org/wiki/Law_of_cosines) to the triangle in the figure.

**Comment by cycle20** [comment]
> The derivation is simply to apply the [law of cosines](https://en.wikipedia.org/wiki/Law_of_cosines) to the triangle in the figure.

@mittinatten thank you for response. :+1:
