### ISSUE TITLE
Questions for understanding codes implementation

### ISSUE THREAD

**Issue by zhongxiang117** [mittinatten/freesasa#87]
Hi Mittinatten,

I am trying to understand the codes implementation via your writing from: http://freesasa.github.io/doxygen/Geometry.html, there are some questions that I feel confused,

1) For the `law of cosine` to calculate `the angle of circle i that is buried due to circle j`, should the angle be calculated by switching the subscript `i` and `j` in numerator? Please check on the attached image:

![image](https://user-images.githubusercontent.com/28009328/203462413-4a14fa65-69cc-47bf-8499-c8a960eaf317.png)

2) For the `arc that exposed in slice`, am I correct in my drawing picture? (Specifically only for that slice)

![image](https://user-images.githubusercontent.com/28009328/203462447-27c275fd-d035-4572-a487-4d68e51bcb5a.png)

3) For the `sum of arcs that exposed in each slice`, looking at your codes, am I correct that the sum was performed on `dash` truncation in the space? (Still, please have a look on the attached picture in above)

I greatly appreciate for your help, thank you very much!

**Comment by zhongxiang117** [comment]
Typo: in the first question in denominator, the square `2` should be `'`(prime).

**Comment by mittinatten** [comment]
Hi, sorry for the delayed response
1. You are right, there is a typo in the documentation, the code uses ` alpha = acos((Ri_prime2 + dij * dij - Rj_prime2) / (2.0 * Ri_prime * dij));`, i.e. there is a plus sign in front of `d_ij`. I will update the docs.
2. The picture is not entirely correct, the delta is the distance between slices, not the distance between a slice and the center of the sphere. So the picture to the left is misleading, the one to the right is correct.
3. I don't know what dash truncation is.

**Comment by zhongxiang117** [comment]
Hi, thanks for your explanation, I guess now I know the codes implementation.

1. Thanks for your update.
2. The picture on the left only shows _that_ `slice`, thanks for your clarification, now it makes more clear to me to understand the `distance` between the `slice`s.
3. I saw in your codes, there is a line: `z = zi - Ri - 0.5 * delta;` in file "sasa_lr.c" line `305`, you can refer to [here](https://github.com/mittinatten/freesasa/blob/master/src/sasa_lr.c#L305), so based on my `question 2`, the summarize is actually performed on the **center** of the `slice`s, which is the meaning of the `dash` lines, am I correct?

Thank you again for your reply!   -xiang

**Comment by zhongxiang117** [comment]
Thank you for your reply and explanations. I am going to close this issue, thank you!
