### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by WenfeiXiao** [mittinatten/freesasa#93]
make[1]: Entering directory '/newhome/xiaowf/peptide_design/freesasa-2.1.2'
Making all in src
make[2]: Entering directory '/newhome/xiaowf/peptide_design/freesasa-2.1.2/src'
g++ -std=gnu++14 -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/   -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cc
mv -f .deps/main.Tpo .deps/main.Po
g++ -std=gnu++14 -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/   -g -O2 -MT cif.o -MD -MP -MF .deps/cif.Tpo -c -o cif.o cif.cc
mv -f .deps/cif.Tpo .deps/cif.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT classifier.o -MD -MP -MF .deps/classifier.Tpo -c -o classifier.o classifier.c
mv -f .deps/classifier.Tpo .deps/classifier.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT classifier_protor.o -MD -MP -MF .deps/classifier_protor.Tpo -c -o classifier_protor.o classifier_protor.c
mv -f .deps/classifier_protor.Tpo .deps/classifier_protor.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT classifier_oons.o -MD -MP -MF .deps/classifier_oons.Tpo -c -o classifier_oons.o classifier_oons.c
mv -f .deps/classifier_oons.Tpo .deps/classifier_oons.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT classifier_naccess.o -MD -MP -MF .deps/classifier_naccess.Tpo -c -o classifier_naccess.o classifier_naccess.c
mv -f .deps/classifier_naccess.Tpo .deps/classifier_naccess.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT coord.o -MD -MP -MF .deps/coord.Tpo -c -o coord.o coord.c
mv -f .deps/coord.Tpo .deps/coord.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT pdb.o -MD -MP -MF .deps/pdb.Tpo -c -o pdb.o pdb.c
mv -f .deps/pdb.Tpo .deps/pdb.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT log.o -MD -MP -MF .deps/log.Tpo -c -o log.o log.c
mv -f .deps/log.Tpo .deps/log.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT sasa_lr.o -MD -MP -MF .deps/sasa_lr.Tpo -c -o sasa_lr.o sasa_lr.c
mv -f .deps/sasa_lr.Tpo .deps/sasa_lr.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT sasa_sr.o -MD -MP -MF .deps/sasa_sr.Tpo -c -o sasa_sr.o sasa_sr.c
mv -f .deps/sasa_sr.Tpo .deps/sasa_sr.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT structure.o -MD -MP -MF .deps/structure.Tpo -c -o structure.o structure.c
mv -f .deps/structure.Tpo .deps/structure.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT node.o -MD -MP -MF .deps/node.Tpo -c -o node.o node.c
mv -f .deps/node.Tpo .deps/node.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT freesasa.o -MD -MP -MF .deps/freesasa.Tpo -c -o freesasa.o freesasa.c
mv -f .deps/freesasa.Tpo .deps/freesasa.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT nb.o -MD -MP -MF .deps/nb.Tpo -c -o nb.o nb.c
mv -f .deps/nb.Tpo .deps/nb.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT util.o -MD -MP -MF .deps/util.Tpo -c -o util.o util.c
mv -f .deps/util.Tpo .deps/util.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT rsa.o -MD -MP -MF .deps/rsa.Tpo -c -o rsa.o rsa.c
mv -f .deps/rsa.Tpo .deps/rsa.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT selection.o -MD -MP -MF .deps/selection.Tpo -c -o selection.o selection.c
In file included from /usr/include/string.h:495,
                 from freesasa_internal.h:10,
                 from selection.c:9:
In function ‘strncpy’,
    inlined from ‘select_area_impl’ at selection.c:728:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
selection.c: In function ‘select_area_impl’:
selection.c:723:19: note: length computed here
  723 |             len = strlen(selection->name);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/selection.Tpo .deps/selection.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT lexer.o -MD -MP -MF .deps/lexer.Tpo -c -o lexer.o lexer.c
mv -f .deps/lexer.Tpo .deps/lexer.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I../third-party/gemmi/include/    -g -O2 -MT parser.o -MD -MP -MF .deps/parser.Tpo -c -o parser.o parser.c
mv -f .deps/parser.Tpo .deps/parser.Po
rm -f libfreesasa.a
ar cru libfreesasa.a classifier.o classifier_protor.o classifier_oons.o classifier_naccess.o coord.o pdb.o log.o sasa_lr.o sasa_sr.o structure.o node.o freesasa.o nb.o util.o rsa.o selection.o lexer.o parser.o   
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libfreesasa.a
g++ -std=gnu++14  -g -O2   -o freesasa main.o cif.o -lc++ libfreesasa.a   -ldl -lm 
/usr/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:513: freesasa] Error 1
make[2]: Leaving directory '/newhome/xiaowf/peptide_design/freesasa-2.1.2/src'
make[1]: *** [Makefile:382: all-recursive] Error 1
make[1]: Leaving directory '/newhome/xiaowf/peptide_design/freesasa-2.1.2'
make: *** [Makefile:321: all] Error 2

**Comment by mittinatten** [comment]
Hmm, this must be a stricter warning set in newer versions of GCC. I had a quick look at the code, and I _think_ it's not an actual error in this case. The quick fix should be configuring with `./configure CFLAGS="-g -O2 -Wno-stringop-overflow"`. I will see if I there's a way fix the underlying problem, but will probably take a while, because of summer holidays.

**Comment by WenfeiXiao** [comment]
> 

Thanks a lot! Have a great summer.

**Comment by mittinatten** [comment]
I fixed the code on the line mentioned in the printout. My compiler doesn't throw this warning, so it could still be problem elsewhere. Can you see if the latest version of code works for you @WenfeiXiao ?
