### ISSUE TITLE
memerr tests fail because a malloc call is replaced by a built-in

### ISSUE THREAD

**Issue by dtelsing** [mittinatten/freesasa#94]
The memerr tests rely on replacing malloc with a wrapper which fails after a certain number of calls. If the malloc call is replaced by the compiler however, this breaks some tests.

When building with gcc version 11.3.0 for i686-unknown-linux-gnu with -O2 optimizations, this lead test_memerr in tests/test_selection.c to dereference a null pointer, because select_atoms (in src/selection.c) continues further than intended and dereferences selection_dummy.atom (==NULL).

Therefore, it would be good to build the library with -fno-builtin-malloc or build the tests separately with that flag enabled.

**Comment by mittinatten** [comment]
I added the flag and far as I can tell it hides all the tests, it also avoids compiling the helper code that does the replacement.

I think using the flag `-fno-builtin-malloc` could be beneficial, but I don't know if it's worth it to set up a complete separate build for the tests.
