### ISSUE TITLE
Windows access violation

### ISSUE THREAD

**Issue by pegerto** [mittinatten/freesasa#95]
Hello, 

I building a small kit for MDAnalisys and found some issues running the  service in windows.

I am using a python implementation but it works correctly in both windows and mac. 

```
 result = freesasa.calc(structure)
```

The output:

```
Windows fatal exception: access violation

Thread 0x000016[28](https://github.com/pegerto/mdakit_sasa/actions/runs/6444612837/job/17497801486#step:8:29) (most recent call first):
  File "C:\Miniconda\envs\mdakit_sasa-test\Lib\threading.py", line 331 in wait

```

Raise a window violation exception in almost all windows services tested by window latest., unfortunatly I do not have a window machine to dig deeper on this issue.  Is there any CI process verifying the implemetation on windows.

**Comment by mittinatten** [comment]
I don't have access to a Windows environment either, so I have no idea what the problem means. I guess there could be problems with the way FreeSASA sets up multithreading (using the pthreads library). You might be able to circumvent this by passing [parameters](https://freesasa.github.io/python/classes.html#freesasa.Parameters) with `n-threads = 1` to [`freesasa.calc`](https://freesasa.github.io/python/functions.html#freesasa.calc)

**Comment by pegerto** [comment]
hi @mittinatten 

Thanks you very much for your guidances, I have implemented your suggestions and I am using `n-threads = 1` in windows and the github CI actions is not longer throwing an exception. 

Regards.
