### ISSUE TITLE
using Free SASA with noncanonical amino acids

### ISSUE THREAD

**Issue by tsamdin** [mittinatten/freesasa#97]
I’m trying to use the python implementation of your FreeSASA software to analyze peptide structures that contain some non-canonical amino acids and covalent modifications. Ultimately, I’d like to have the results printed to a PDB file. I can get FreeSASA to run on proteins without these modifications.

I’ve made a new protor.config file that includes the parameters for the noncanonical AA’s, though I’m not sure it’s being read by ‘structure’ when I include it as a classifier input. 

result.write_pdb outputs a file without the non-canonical amino acids or modifications, making me think that those residues/atoms were skipped over?

I’d appreciate any help or guidance you could provide. Most of what I know of python is self-taught, so I’ve been stumbling through this project.

**Comment by tsamdin** [comment]
Please ignore my earlier comment. I think I resolved it by using: 

freesasa.Structure(fileName, options = {'hetatm' : True})

Also I realized that I posted this in your C repository, instead of the python one for FreeSASA. 

Thank you for making this tool!

**Comment by mittinatten** [comment]
Hi, and sorry, your issue was lost in a spam filter or something on my side. But glad to hear it worked out!
